apiVersion : apps/v1
kind: Deployment
metadata:
  name: "simokubernetes-fd56"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "simokubernetes-fd56"
  template:
    metadata:
      labels:
        app: "simokubernetes-fd56"
    spec:
      containers:
        - name: "simokubernetes-fd56"
          image: "dockercorerestapi700.azurecr.io/simokubernetes"
          ports:
          - containerPort: 3000