on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dockercorerestapi700.azurecr.io
        username: ${{ secrets.acr_dockercorerestapi700_username }}
        password: ${{ secrets.acr_dockercorerestapi700_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t dockercorerestapi700.azurecr.io/simokubernetes:${{ github.sha }}
        docker push dockercorerestapi700.azurecr.io/simokubernetes:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_simokubernetes_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep simokubernetes9f0c | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace simokubernetes9f0c`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: simokubernetes9f0c
        container-registry-url: dockercorerestapi700.azurecr.io
        container-registry-username: ${{ secrets.acr_dockercorerestapi700_username }}
        container-registry-password: ${{ secrets.acr_dockercorerestapi700_password }}
        secret-name: simokubernetdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: simokubernetes9f0c
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          dockercorerestapi700.azurecr.io/simokubernetes:${{ github.sha }}
        imagepullsecrets: |
          simokubernetdockerauth